apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ii2p78jw1-java-springboot
  janus-idp.io/tekton: ii2p78jw1-java-springboot
  backstage.io/kubernetes-id: ii2p78jw1-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ii2p78jw1-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
